### ISSUE TITLE
"Update now" do not working on Fedora Linux Workstation 41 fresh install

### ISSUE THREAD

**Issue by ang-63** [purejava/fedora-update#25]
Hi!
When i click on "update now" i get error "Execution of "gnome-terminal -- /bin/sh -c "sudo dnf upgrade; echo ...
Command not found.

Howto fix that?

**Comment by purejava** [comment]
Hi,

probably the `gnome-terminal` is not installed on your system and so execution of this command by the extension fails.

Either install it or replace the command to be executed string in the advanced preferences of the extension with a terminal software, that _is_ installed.

The first part of the command to be executed string is the executable binary of the terminal software, like you run it on the CLI.

**Comment by ang-63** [comment]
Hi!
Gnome terminal definitely installed.


пн, 4 нояб. 2024 г., 22:15 Ralph Plawetzki ***@***.***>:

**Comment by mhagnumdw** [comment]
@ang-63 , what if you edit the command line to launch with the full path of gnome-terminal? In my case it is: /usr/bin/gnome-terminal

In Settings > Advanced settings > Command to update packages

**Comment by purejava** [comment]
> Hi! Gnome terminal definitely installed. 

I don't think so. In Fedora 41, Ptyxis is the new default terminal app, that replaces GNOME Terminal. See https://fedoramagazine.org/whats-new-fedora-workstation-41/. So on a freshly installed Fedora 41 the `gnome-terminal` package is missing, but the `ptyxis` package is installed instead.

As I said before, either install the `gnome-terminal` package or replace the command to be executed string in the advanced preferences of the extension with `ptyxis -- /bin/sh -c \"sudo dnf upgrade; echo Done - Press enter to exit; read _\" "`.

Nevertheless, I made the change in the extension too and submitted version v23 of the extension for release, so that there is no need to change anything on a newly installed Fedora 41.

**Comment by ang-63** [comment]
Thank you. I just check app details on gnome software center and its
gnone-terminal.
But i will try.

вт, 5 нояб. 2024 г., 10:10 Ralph Plawetzki ***@***.***>:

**Comment by saxa** [comment]
I can confirm that something is not set up correctly by default, I had a ptyxis listed and in the settings as the terminal.
` dnf list ptyxis
Updating and loading repositories:
Repositories loaded.
Installed packages
ptyxis.x86_64 47.3-1.fc41 <unknown>
`
But trying to list it or run it it was not there, so I had to `dfn remove ptyxis` and then `dnf install ptyxis` and this solved the issue seems.
